// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:a098f132-e680-4a13-954a-51cde1533f58',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'nilesmcgiverreactblo-hosting-mobilehub-2123206351',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3qc86b7kp6ids.cloudfront.net',
    'aws_mobile_analytics_app_id': '701b24b370cf4c9ea40ad27a234a657d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '6030f8fb-3f21-400b-978e-78b249032598',
    'aws_project_name': 'niles.mcgiver.reactblog',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'nilesmcgiverreactblo-mobilehub-2123206351',
}

export default awsmobile;
